# Generated by Django 5.2.16 on 2026-07-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="имя")),
                ("headline", models.CharField(max_length=200, verbose_name="кто я одной строкой")),
                ("bio_md", models.TextField(blank=True, verbose_name="о себе (Markdown)")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile/", verbose_name="фото"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="город / часовой пояс"
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True, default=list, verbose_name="навыки (список строк)"
                    ),
                ),
                (
                    "socials",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="контакты {github, telegram, email…}"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="SEO-описание главной"
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль",
                "verbose_name_plural": "профиль",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug (URL)")),
                ("title", models.CharField(max_length=120, verbose_name="название")),
                ("tagline", models.CharField(max_length=200, verbose_name="одной строкой")),
                (
                    "description_md",
                    models.TextField(blank=True, verbose_name="описание (Markdown)"),
                ),
                ("role", models.CharField(blank=True, max_length=120, verbose_name="роль")),
                (
                    "org",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="компания / контекст"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("work", "работа"),
                            ("pet", "пет-проект"),
                            ("oss", "open source"),
                            ("freelance", "фриланс"),
                        ],
                        default="pet",
                        max_length=20,
                        verbose_name="тип",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="начало")),
                (
                    "period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="конец (пусто = по настоящее время)"
                    ),
                ),
                (
                    "stack",
                    models.JSONField(blank=True, default=list, verbose_name="стек (список строк)"),
                ),
                (
                    "highlights",
                    models.JSONField(
                        blank=True, default=list, verbose_name="ключевые фишки (список строк)"
                    ),
                ),
                (
                    "links",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="ссылки {live, repo, case}"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="covers/", verbose_name="обложка"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "живой"),
                            ("wip", "в разработке"),
                            ("archived", "архив"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                ("is_published", models.BooleanField(default=False, verbose_name="опубликован")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="закреплён вверху"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="порядок")),
                (
                    "uptime_monitor_slug",
                    models.CharField(
                        blank=True,
                        help_text="Связь с uptime-чекером для живого статус-бейджа (Phase 4)",
                        max_length=50,
                        verbose_name="slug монитора uptime",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "проект",
                "verbose_name_plural": "проекты",
                "ordering": ["-is_featured", "sort_order", "-period_start"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "sort_order"], name="content_pro_is_publ_ceb654_idx"
                    )
                ],
            },
        ),
    ]
