# Generated by Django 6.1.1 on 2026-09-24 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_seed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="height",
                        upload_to="gallery/",
                        verbose_name="изображение",
                        width_field="width",
                    ),
                ),
                (
                    "thumb",
                    models.ImageField(upload_to="gallery/thumbs/", verbose_name="превью"),
                ),
                (
                    "width",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="ширина"),
                ),
                (
                    "height",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="высота"),
                ),
                (
                    "caption",
                    models.CharField(blank=True, max_length=200, verbose_name="подпись"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.project",
                        verbose_name="проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "кадр галереи",
                "verbose_name_plural": "галерея",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
